version: "3.8"

services:
  core:
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    build:
      args:
        - BASE_IMAGE=nvcr.io/nvidia/pytorch:22.04-py3
      context: ../../
      dockerfile: environments/Dockerfile
    image: "pytorch:22.04"
    container_name: pytorch
    shm_size: 16gb
    restart: always
    user: 1000:1000
    tty: true
    volumes:
      - ../../:/home/challenger/ascender
    ports:
      - 8888:6060
      - 6006:6006
